name: nicold-workflow-name

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v3

      - name: Set the value
        id: step_one
        run: |
          echo "action_state={$(date)}" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}"
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo my first step

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ls -la
          echo test, and deploy your project.
