name: nicold-workflow-name

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v3

      - name: Set the build date and time
        id: step_build_date_and_time
        run: |
          echo "build_timestamp=$(date)" >> $GITHUB_ENV
          cat subdir/another-file.md
          sed -i 's/__BUILDDATE__/$(date)/g' subdir/another-file.md  
          cat subdir/another-file.md
        
      - name: Use the build date
        id: step_replace
        run: |
          echo "build timestamp: ${{ env.build_timestamp }}"
          
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ls -la
          echo test, and deploy your project.
